### ISSUE TITLE
Add test to fail if erc.yml is missing

### ISSUE THREAD

**Issue by TeKraft** [o2r-project/o2r-substituter#4]
Currently it is not checked if there exists an `erc.yml` file.

**Comment by nuest** [comment]
Right... you should not delete one that exists, but parse it an replace the run command.

**Comment by nuest** [comment]
Let me clarify: You should _check_ if it exists, and return an error when it does not. The base ERC will always have one _if a job for it exists_. You can mention that in the error message:

```json
400

{"error":"missing configuration file in base compendium, please execute a job for the base compedium first"}
```

**Comment by TeKraft** [comment]
https://github.com/TeKraft/o2r-substituter/commit/184f6f0b5412df2a63ca532a1edade756c2f7964

this should fix this issue

**Comment by nuest** [comment]
@TeKraft We need to add a test to handle the case of a missing erc.yml - or is there already one?

**Comment by TeKraft** [comment]
fixed with this PR https://github.com/o2r-project/o2r-substituter/pull/8
